package rawrr

import "github.com/nazhard/go-simple-crud/pkg/models"

var Users = []models.User{
  {
    Id: 1,
    Name: "Agus",
    Phone: "62xxx-xxxx-xxxx",
    Email: "Agus@example.com",
    Age: 19,
    Student: true,
  },
  {
    Id: 2,
    Name: "Fadhil",
    Phone: "62xxx-xxxx-xxxx",
    Email: "twins@example.com",
    Age: 23,
    Student: false,
  },
  {
    Id: 3,
    Name: "Wawan",
    Phone: "62xxx-xxxx-xxxx",
    Email: "Wawan@example.com",
    Age: 29,
    Student: false,
  },
  {
    Id: 4,
    Name: "Agan",
    Phone: "62xxx-xxxx-xxxx",
    Email: "krocofb@example.com",
    Age: 18,
    Student: true,
  },
  {
    Id: 5,
    Name: "Fadlan",
    Phone: "62xxx-xxxx-xxxx",
    Email: "twins@example.com",
    Age: 23,
    Student: false,
  },
  {
    Id: 6,
    Name: "Mansur",
    Phone: "62xxx-xxxx-xxxx",
    Email: "trillionare@example.com",
    Age: 45,
    Student: false,
  },
  {
    Id: 7,
    Name: "Luwak",
    Phone: "62xxx-xxxx-xxxx",
    Email: "kopi@example.com",
    Age: 96,
    Student: false,
  },
  {
    Id: 8,
    Name: "Asep Bensin",
    Phone: "62xxx-xxxx-xxxx",
    Email: "asepbumi@example.com",
    Age: 19,
    Student: true,
  },
  {
    Id: 9,
    Name: "Samsul Arif",
    Phone: "62xxx-xxxx-xxxx",
    Email: "samsul@example.com",
    Age: 34,
    Student: false,
  },
  {
    Id: 10,
    Name: "Nazhard",
    Phone: "62xxx-xxxx-xxxx",
    Email: "asli.masih.pemula@example.com",
    Age: 15,
    Student: true,
  },
}